contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('<int:contact_id>/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'

    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%M/')
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL, blank=True, null=True
        )
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, blank=True, null=True
        )
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request,
        'contact/index.html'
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from contact.models import Contact


def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    contact_name = f'{single_contact.first_name} {single_contact.last_name} - '

    context = {
        'contact': single_contact,
        'site_title': contact_name,
    }

    return render(
        request,
        'contact/contact.html',
        
        context
    )


def index(request):
    contacts = Contact.objects \
        .filter(show=True).\
        order_by('-id')[:10]
    
    
    

    context = {
        'contacts': contacts,
        'site_title': 'Contatos -',
        
    }

    return render(
        request,
        'contact/index.html',
        
        context
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects \
        .filter(show=True)\
        .filter(
            Q(id__iexact=search_value) |
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value)
            )\
        .order_by('-id')[:10]
    
    
    

    context = {
        'contacts': contacts,
        'site_title': 'Contatos -',
        
    }

    return render(
        request,
        'contact/index.html',
        
        context
    )

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>

        <p><b>ID:</b> {{contact.id}}</p>
        <p><b>Primeiro nome:</b> {{contact.first_name}}</p>
        <p><b>Ultimo nome:</b> {{contact.last_name}}</p>
        <p><b>Telefone:</b> {{contact.phone}}</p>
        <p><b>Data do cadastro:</b> {{contact.created_date}}</p>
        <p><b>Descrição:</b> {{contact.description}}</p>
        <p><b>Situação:</b> {{contact.category.name}}</p>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="responsive-table">
    <table class="contacts-table">
      <caption class="table-caption">
        Contacts
      </caption>
      <thead>
        <tr class="table-row table-row-header">
          <th class="table-header">ID</th>
          <th class="table-header">First Name</th>
          <th class="table-header">Last Name</th>
          <th class="table-header">Phone</th>
          <th class="table-header">E-mail</th>
        </tr> 
      </thead>
      <tbody>
        {% for contact in contacts %}
          <tr class="table-row">
            <td class="table-cel">
              <a 
              href="{% url "contact:contact" contact.id %}" 
              class="table-link"
              >
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">
                {{ contact.first_name }}
            </td>
            <td class="table-cel">
              {{ contact.last_name }}
            </td>
            <td class="table-cel">
              {{ contact.phone }}
            </td>
            <td class="table-cel">
              {{ contact.email }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}